export type MediaType = 
  "album"
  | "announcement"
  | "artist"
  | "audiobook"
  | "flow_stream"
  | "folder"
  | "genre"
  | "playlist"
  | "plugin_source"
  | "podcast"
  | "podcast_episode"
  | "radio"
  | "sound_effect"
  | "track"
  | "unknown"